package com.example.copymeli.model.response

class ProductList {
    val list = mutableListOf(
        Product(
            1,
            "Campera urbana",
            "Urban",
            25.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("columbia", "visa")),
            "21/02/23",
            false,
            false,
            Owner("luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "La Campera Urbana Lotto Hs May Hombre es una prenda moderna y versátil para los hombres que buscan estilo y comodidad en su vestimenta diaria.",
            "20%",
            4.99,
            "new york",
            "https://www.stockcenter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw630c4b07/products/LONIFW230473/LONIFW230473-1.JPG"
        ),
        Product(
            2,
            "Remera cuello en v",
            "Fashion",
            39.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia", "visa")),
            "21/02/23",
            false,
            false,
            Owner("luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Remera básica lisa de jersey de algodón 24/1. Con escote en V.",
            "20%",
            4.99,
            "new york",
            "https://forever21.com.ar/media/catalog/product/cache/06cfaa02c67cf3a5c3c05d775284c631/r/e/remera-hombre-basica-escote-v-forever21-r2m091002-100_1__1_3.jpg"
        ),
        Product(
            3,
            "Remera cuello redondo",
            "SunDresses",
            29.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia", "Visa")),
            "21/02/23",
            false,
            false,
            Owner("Luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Remera básica lisa de jersey de algodón 24/1. Con cuello redondo",
            "20%",
            4.99,
            "new york",
            "https://forever21.com.ar/media/catalog/product/cache/06cfaa02c67cf3a5c3c05d775284c631/r/e/remera-hombre-basica-escote-v-forever21-r2m091002-100_1__1_3.jpg"
        ),
        Product(
            4,
            "Buzo cuello redondo",
            "UrbanRider",
            79.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia", "Visa")),
            "21/02/23",
            false,
            false,
            Owner("Luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Buzo liso de jersey de algodón 24/1. Con escote en V.",
            "20%",
            4.99,
            "new york",
            "https://deliverind.com.ar/wp-content/uploads/2022/10/BUZO-OVERSIZE-RUSTICO-22-PORTADA-10-scaled.jpg.webp"
        ),
        Product(
            5,
            "Buzo capucha",
            "CozyKnits",
            45.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia", "Visa")),
            "21/02/23",
            false,
            false,
            Owner("Luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Buzo con capucha liso de jersey de algodón",
            "20%",
            4.99,
            "new york",
            "https://remerasya.com/media/catalog/product/cache/839e5c25c645eac744603bf9726fb4fd/b/u/buzo_con_capucha_friza_pesada_negro_1.jpg"
        ),
        Product(
            6,
            "Zapatillas deportivas",
            "Nike",
            89.99,
            70.00,
            "%15",
            "$",
            false,
            Promotion(70.00, 3, Cards("Mastercard", "Visa")),
            "15/03/23",
            true,
            true,
            Owner("Maria", "mariadeportes"),
            120,
            4.5,
            82.00,
            "Las zapatillas deportivas Nike Air Max ofrecen comodidad y estilo para tus actividades deportivas y uso diario.",
            "15%",
            0.0,
            "los angeles",
            "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/68e68a11-7d25-4680-bde3-7e93a8c9fed9/air-jordan-3-retro-big-kids-shoes-Trq8Fk.png"
        ),
        Product(
            7,
            "Reloj de pulsera",
            "Casio",
            39.99,
            30.00,
            "%25",
            "$",
            false,
            Promotion(30.00, 4, Cards("Amex", "Visa")),
            "05/04/23",
            false,
            true,
            Owner("Carlos", "timezone"),
            65,
            4.2,
            42.00,
            "Un reloj de pulsera clásico de la marca Casio, perfecto para cualquier ocasión.",
            "25%",
            0.0,
            "miami",
            "https://www.casio.com/content/dam/casio/product-info/locales/latin/es-ar/timepiece/product/watch/G/GM/GMA/gma-s114rx-7a/assets/GMA-S114RX-7A_N.png.transform/main-visual-pc/image.png"
        ),
        Product(
            8,
            "Auriculares inalámbricos",
            "Sony",
            89.99,
            75.00,
            "%16",
            "$",
            false,
            Promotion(75.00, 2, Cards("Mastercard", "Discover")),
            "12/05/23",
            true,
            true,
            Owner("Ana", "sonylover"),
            90,
            4.8,
            85.00,
            "Auriculares inalámbricos con excelente calidad de sonido y diseño ergonómico de Sony.",
            "16%",
            5.99,
            "tokyo",
            "https://www.sony.com.ar/image/7eaefbd8262b148fbeff063d409cb5da?fmt=pjpeg&wid=1014&hei=396&bgcolor=F1F5F9&bgc=F1F5F9"
        ),
        Product(
            9,
            "Mesa de escritorio",
            "IKEA",
            129.99,
            110.00,
            "%15",
            "$",
            true,
            Promotion(110.00, 1, Cards("Palpal", "Visa")),
            "05/04/23",
            true,
            true,
            Owner("Elena", "homestyler"),
            35,
            4.5,
            120.00,
            "Una mesa de escritorio elegante y funcional de IKEA, ideal para tu espacio de trabajo en casa.",
            "15%",
            0.0,
            "stockholm",
            "https://www.casio.com/content/dam/casio/product-info/locales/latin/es-ar/timepiece/product/watch/G/GM/GMA/gma-s114rx-7a/assets/GMA-S114RX-7A_N.png.transform/main-visual-pc/image.png"
        )

    )

}

data class Product(
    val id: Int,
    val name: String,
    val brand: String,
    val price: Double,
    val offersPrice: Double,
    val offersPercent: String,
    val money: String,
    val freeSend: Boolean,
    val promotion: Promotion,
    val date: String,
    val isFavorite: Boolean,
    val isPromotion: Boolean,
    val owner: Owner,
    val sold: Int,
    val punctuation: Double,
    val oldPrice: Double,
    val description: String,
    val discount: String,
    val sendPrice: Double,
    val location: String,
    val url: String
)

data class Promotion(val price: Double, val dues: Int, val cards: Cards)
data class Owner(val name: String, val alias: String)
data class Cards(val card1: String, val card2: String)