package com.example.copymeli.model.response

class ProductList {
    val list = mutableListOf(
        Product(
            1,
            "Campera urbana",
            "Urban",
            25.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6,Cards("columbia","visa")),
            "21/02/23",
            false,
            false,
            Owner("luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "La Campera Urbana Lotto Hs May Hombre es una prenda moderna y versátil para los hombres que buscan estilo y comodidad en su vestimenta diaria.",
            "20%",
            4.99,
            "new york",
            "https://www.stockcenter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw630c4b07/products/LONIFW230473/LONIFW230473-1.JPG"
        ),
        Product(
            2,
            "Remera cuello en v",
            "Fashion",
            39.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6,Cards("Columbia","visa")),
            "21/02/23",
            false,
            false,
            Owner("luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Remera básica lisa de jersey de algodón 24/1. Con escote en V.",
            "20%",
            4.99,
            "new york",
            "https://forever21.com.ar/media/catalog/product/cache/06cfaa02c67cf3a5c3c05d775284c631/r/e/remera-hombre-basica-escote-v-forever21-r2m091002-100_1__1_3.jpg"
        ),
        Product(
                3,
        "Remera cuello redondo",
        "SunDresses",
            29.99,
        20.00,
        "%20",
        "$",
        false,
        Promotion(15.00, 6, Cards("Columbia","Visa")),
        "21/02/23",
        false,
        false,
        Owner("Luis", "flexiplus"),
        43,
        4.00,
        43.00,
        "Remera básica lisa de jersey de algodón 24/1. Con cuello redondo",
        "20%",
        4.99,
        "new york",
        "https://forever21.com.ar/media/catalog/product/cache/06cfaa02c67cf3a5c3c05d775284c631/r/e/remera-hombre-basica-escote-v-forever21-r2m091002-100_1__1_3.jpg"
    ),
        Product(
            4,
            "Buzo cuello redondo",
            "UrbanRider",
            79.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia","Visa")),
            "21/02/23",
            false,
            false,
            Owner("Luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Buzo liso de jersey de algodón 24/1. Con escote en V.",
            "20%",
            4.99,
            "new york",
            "https://deliverind.com.ar/wp-content/uploads/2022/10/BUZO-OVERSIZE-RUSTICO-22-PORTADA-10-scaled.jpg.webp"
        ),
        Product(
            5,
            "Buzo capucha",
            "CozyKnits",
            45.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia","Visa")),
            "21/02/23",
            false,
            false,
            Owner("Luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Buzo con capucha liso de jersey de algodón",
            "20%",
            4.99,
            "new york",
            "https://remerasya.com/media/catalog/product/cache/839e5c25c645eac744603bf9726fb4fd/b/u/buzo_con_capucha_friza_pesada_negro_1.jpg"
        )

    )

}

data class Product(
    val id: Int,
    val name: String,
    val brand: String,
    val price: Double,
    val offersPrice: Double,
    val offersPercent: String,
    val money: String,
    val freeSend: Boolean,
    val promotion: Promotion,
    val date: String,
    val isFavorite: Boolean,
    val isPromotion: Boolean,
    val owner: Owner,
    val sold: Int,
    val punctuation: Double,
    val oldPrice: Double,
    val description: String,
    val discount: String,
    val sendPrice: Double,
    val location: String,
    val url: String
)

data class Promotion(val price: Double, val dues: Int, val cards: Cards )
data class Owner(val name: String, val alias: String)
data class Cards(val card1: String, val card2: String )