package com.example.copymeli.model.response

class ProductList {
    val list = mutableListOf(
        Product(
            1,
            "Campera urbana",
            "Urban",
            25.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("columbia", "visa")),
            "21/02/23",
            false,
            false,
            Owner("luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "La Campera Urbana Lotto Hs May Hombre es una prenda moderna y versátil para los hombres que buscan estilo y comodidad en su vestimenta diaria.",
            "20%",
            4.99,
            "new york",
            "https://www.stockcenter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw630c4b07/products/LONIFW230473/LONIFW230473-1.JPG"
        ),
        Product(
            2,
            "Remera cuello en v",
            "Fashion",
            39.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia", "visa")),
            "21/02/23",
            false,
            false,
            Owner("luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Remera básica lisa de jersey de algodón 24/1. Con escote en V.",
            "20%",
            4.99,
            "new york",
            "https://forever21.com.ar/media/catalog/product/cache/06cfaa02c67cf3a5c3c05d775284c631/r/e/remera-hombre-basica-escote-v-forever21-r2m091002-100_1__1_3.jpg"
        ),
        Product(
            3,
            "Remera cuello redondo",
            "SunDresses",
            29.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia", "Visa")),
            "21/02/23",
            false,
            false,
            Owner("Luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Remera básica lisa de jersey de algodón 24/1. Con cuello redondo",
            "20%",
            4.99,
            "new york",
            "https://forever21.com.ar/media/catalog/product/cache/06cfaa02c67cf3a5c3c05d775284c631/r/e/remera-hombre-basica-escote-v-forever21-r2m091002-100_1__1_3.jpg"
        ),
        Product(
            4,
            "Buzo cuello redondo",
            "UrbanRider",
            79.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia", "Visa")),
            "21/02/23",
            false,
            false,
            Owner("Luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Buzo liso de jersey de algodón 24/1. Con escote en V.",
            "20%",
            4.99,
            "new york",
            "https://deliverind.com.ar/wp-content/uploads/2022/10/BUZO-OVERSIZE-RUSTICO-22-PORTADA-10-scaled.jpg.webp"
        ),
        Product(
            5,
            "Buzo capucha",
            "CozyKnits",
            45.99,
            20.00,
            "%20",
            "$",
            false,
            Promotion(15.00, 6, Cards("Columbia", "Visa")),
            "21/02/23",
            false,
            false,
            Owner("Luis", "flexiplus"),
            43,
            4.00,
            43.00,
            "Buzo con capucha liso de jersey de algodón",
            "20%",
            4.99,
            "new york",
            "https://remerasya.com/media/catalog/product/cache/839e5c25c645eac744603bf9726fb4fd/b/u/buzo_con_capucha_friza_pesada_negro_1.jpg"
        ),
        Product(
            6,
            "Zapatillas deportivas",
            "Nike",
            89.99,
            70.00,
            "%15",
            "$",
            false,
            Promotion(70.00, 3, Cards("Mastercard", "Visa")),
            "15/03/23",
            true,
            true,
            Owner("Maria", "mariadeportes"),
            120,
            4.5,
            82.00,
            "Las zapatillas deportivas Nike Air Max ofrecen comodidad y estilo para tus actividades deportivas y uso diario.",
            "15%",
            0.0,
            "los angeles",
            "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/68e68a11-7d25-4680-bde3-7e93a8c9fed9/air-jordan-3-retro-big-kids-shoes-Trq8Fk.png"
        ),
        Product(
            7,
            "Reloj de pulsera",
            "Casio",
            39.99,
            30.00,
            "%25",
            "$",
            false,
            Promotion(30.00, 4, Cards("Amex", "Visa")),
            "05/04/23",
            false,
            true,
            Owner("Carlos", "timezone"),
            65,
            4.2,
            42.00,
            "Un reloj de pulsera clásico de la marca Casio, perfecto para cualquier ocasión.",
            "25%",
            0.0,
            "miami",
            "https://www.casio.com/content/dam/casio/product-info/locales/latin/es-ar/timepiece/product/watch/G/GM/GMA/gma-s114rx-7a/assets/GMA-S114RX-7A_N.png.transform/main-visual-pc/image.png"
        ),
        Product(
            8,
            "Auriculares inalámbricos",
            "Sony",
            89.99,
            75.00,
            "%16",
            "$",
            false,
            Promotion(75.00, 2, Cards("Mastercard", "Discover")),
            "12/05/23",
            true,
            true,
            Owner("Ana", "sonylover"),
            90,
            4.8,
            85.00,
            "Auriculares inalámbricos con excelente calidad de sonido y diseño ergonómico de Sony.",
            "16%",
            5.99,
            "tokyo",
            "https://www.sony.com.ar/image/7eaefbd8262b148fbeff063d409cb5da?fmt=pjpeg&wid=1014&hei=396&bgcolor=F1F5F9&bgc=F1F5F9"
        ),
        Product(
            9,
            "Mesa de escritorio",
            "IKEA",
            129.99,
            110.00,
            "%15",
            "$",
            true,
            Promotion(110.00, 1, Cards("Palpal", "Visa")),
            "05/04/23",
            true,
            true,
            Owner("Elena", "homestyler"),
            35,
            4.5,
            120.00,
            "Una mesa de escritorio elegante y funcional de IKEA, ideal para tu espacio de trabajo en casa.",
            "15%",
            0.0,
            "stockholm",
            "https://www.casio.com/content/dam/casio/product-info/locales/latin/es-ar/timepiece/product/watch/G/GM/GMA/gma-s114rx-7a/assets/GMA-S114RX-7A_N.png.transform/main-visual-pc/image.png"
        ),
        Product(
            10,
            "Botella de vino reserva",
            "VinedosEjemplo",
            29.99,
            25.00,
            "%17",
            "$",
            false,
            Promotion(15.00, 6, Cards("columbia", "visa")),
            "21/02/23",
            false,
            true,
            Owner("Roberto", "wineconnoisseur"),
            20,
            4.00,
            30.00,
            "Un exquisito vino reserva con sabor y aroma intenso de VinedosEjemplo.",
            "20%",
            4.99,
            "madrid",
            "https://www.brancastore.com.ar/902-large_default/combo-fabre-montmayou-terruno-reserva-malbeccabernet-franc.jpg"
        ),
        Product(
            11,
            "Vestido Floral",
            "Fashionista",
            34.50,
            29.99,
            "%10",
            "$",
            false,
            Promotion(25.00, 3, Cards("mastercard", "amex")),
            "15/03/23",
            true,
            true,
            Owner("Maria", "fashionlover"),
            78,
            4.50,
            33.00,
            "Este hermoso vestido floral es perfecto para lucir elegante en cualquier ocasión especial.",
            "10%",
            0.00,
            "paris",
            "https://www.google.com/imgres?imgurl=https%3A%2F%2Fimages.hola.com%2Fimagenes%2Fmoda%2Ftendencias%2F20230308227207%2Fmejores-vestidos-de-flores%2F1-211-666%2Fvestidofloreslook1-m.jpg%3Ftx%3Dw_680&tbnid=lIsahIPelXuZqM&vet=12ahUKEwjR7vqZ7aiAAxVykZUCHW2IDQsQMygDegUIARD0AQ..i&imgrefurl=https%3A%2F%2Fwww.hola.com%2Fmoda%2Ftendencias%2Fgaleria%2F20230308227207%2Fmejores-vestidos-de-flores%2F1%2F&docid=-N9xvDXmaLvVPM&w=680&h=680&q=vestido%20floral&ved=2ahUKEwjR7vqZ7aiAAxVykZUCHW2IDQsQMygDegUIARD0AQ"
        ),
        Product(
            12,
            "Zapatillas deportivas",
            "Adidas",
            59.99,
            50.00,
            "%15",
            "$",
            false,
            Promotion(45.00, 4, Cards("visa", "diners")),
            "10/04/23",
            false,
            true,
            Owner("Juan", "fitguy"),
            300,
            4.70,
            12.50,
            "Zapatillas deportivas alto impacto running",
            "20%",
            199.99,
            "caballito",
            "https://sporting.vtexassets.com/arquivos/ids/464761-800-800?v=637794890123770000&width=800&height=800&aspect=true"
        ),
        Product(
            13,
            "parlantes",
            "Samsung",
            199.99,
            179.00,
            "%10",
            "$",
            true,
            Promotion(165.00, 12, Cards("Columbia", "Visa")),
            "05/05/23",
            true,
            true,
            Owner("Carolina", "techgeek"),
            30,
            4.70,
            199.00,
            "Parlantes importados samsung, sonido extremo inalambricos",
            "10%",
            2.00,
            "tokyo",
            "https://medias.musimundo.com/medias/00682026-148130-148130-01-148130-01.jpg-size515?context=bWFzdGVyfGltYWdlc3wzMjYxN3xpbWFnZS9qcGVnfGg4Ny9oOWYvMTA0NTM1ODMyNjU4MjIvMDA2ODIwMjYtMTQ4MTMwLTE0ODEzMF8wMS0xNDgxMzBfMDEuanBnX3NpemU1MTV8ZTI1YmI4ZmFkODczZWMwMjQ4MzE1YTUzMjJmMWJlOGMzMzNiNDYyY2Y3MjM3MDRhOTQ3YzM4OGRmMjhjZWY5OQ"
        ),
        Product(
            14,
            "Reloj de pulsera",
            "Casio",
            79.99,
            69.90,
            "%13",
            "$",
            true,
            Promotion(59.00, 6, Cards("Columbia", "Visa")),
            "20/06/23",
            true,
            true,
            Owner("Roberto", "time lover"),
            60,
            4.90,
            80.00,
            "Este elegante reloj de pulsera casio complementará tu look con estilo y precisión",
            "13%",
            3.99,
            "london",
            "https://www.google.com/imgres?imgurl=https%3A%2F%2Favantjoyas.com%2Fwp-content%2Fuploads%2FAvant-Joyas-Reloj-Casio-A700WMG-9A.jpg&tbnid=pdwBK50WhCC8wM&vet=12ahUKEwjHxIDF7KiAAxXtp5UCHUCxDGIQMygOegUIARCjAw..i&imgrefurl=https%3A%2F%2Favantjoyas.com%2Fproducto%2Freloj-casio-a700wmg-9a%2F&docid=1IXjpbds1sJXjM&w=1000&h=1000&q=reloj%20casio&ved=2ahUKEwjHxIDF7KiAAxXtp5UCHUCxDGIQMygOegUIARCjAw"
        ),
        Product(
            15,
            "Escritorio PC",
            "paquito",
            130.99,
            90.00,
            "%15",
            "$",
            false,
            Promotion(70.00, 3, Cards("Mastercard", "Visa")),
            "15/05/23",
            false,
            false,
            Owner("Carlos", "cartucho"),
            20,
            3.5,
            82.00,
            "Lindo escritorio para poder trabajar desde casa o jugar en la compu.",
            "15%",
            0.0,
            "mar del plata",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDXccLcHWKij6kauka3c_Wmjmy3sTsbz0Yl4zIRIZ58WscthS0JikgHKJ_5Mgd3TdoXzU&usqp=CAU"
        ),
        Product(
            16,
            "pintura",
            "alba",
            20.99,
            18.00,
            "%15",
            "$",
            true,
            Promotion(17.90, 5, Cards("Amex", "Visa")),
            "10/06/23",
            true,
            true,
            Owner("joaquin", "full Painting"),
            60,
            4.9,
            80.00,
            "Este elegante reloj de pulsera casio complementará tu look con estilo y precisión.",
            "13%",
            0.0,
            "london",
            "https://www.google.com/imgres?imgurl=https%3A%2F%2Favantjoyas.com%2Fwp-content%2Fuploads%2FAvant-Joyas-Reloj-Casio-A700WMG-9A.jpg&tbnid=pdwBK50WhCC8wM&vet=12ahUKEwjHxIDF7KiAAxXtp5UCHUCxDGIQMygOegUIARCjAw..i&imgrefurl=https%3A%2F%2Favantjoyas.com%2Fproducto%2Freloj-casio-a700wmg-9a%2F&docid=1IXjpbds1sJXjM&w=1000&h=1000&q=reloj%20casio&ved=2ahUKEwjHxIDF7KiAAxXtp5UCHUCxDGIQMygOegUIARCjAw"
        ),
        Product(
            17,
            "parlantes inalámbricos",
            "samsung",
            45.99,
            35.00,
            "%19",
            "$",
            true,
            Promotion(42.00, 5, Cards("Mastercard", "Discover")),
            "20/05/23",
            true,
            true,
            Owner("Benjamin", "benjamusic"),
            90,
            4.8,
            85.00,
            "parlantes de alta calidad de sonido efecto surround.",
            "19%",
            5.99,
            "palermo",
            "https://medias.musimundo.com/medias/00464018-144762-144762-01-144762-01.jpg-size515?context=bWFzdGVyfGltYWdlc3wxMDkyMDB8aW1hZ2UvanBlZ3xoNGIvaDA5LzEwMzgxMTQ3NDcxOTAyLzAwNDY0MDE4LTE0NDc2Mi0xNDQ3NjJfMDEtMTQ0NzYyXzAxLmpwZ19zaXplNTE1fDViZjNiMDU0YzVjNTA3MDI5OTg4MjU2N2ExYTM1YzRmYTFiMzczYjZkOTc3ODY1YzY0NTQ1NTliNmNkODYxMWM"
        ),
        Product(
            18,
            "colchón",
            "belmo",
            129.99,
            110.00,
            "%15",
            "$",
            true,
            Promotion(110.00, 1, Cards("Palpal", "Visa")),
            "05/04/23",
            true,
            true,
            Owner("Carlos", "sueñolar"),
            35,
            4.9,
            120.00,
            "excelente colchón ,suavidad y confort.",
            "15%",
            0.0,
            "villa crespo",
            "https://www.bedtime.com.ar/img_productos/colchones-classic-elite-sistema-pocket-1-06121240.webp"
        )

    )

}

data class Product(
    val id: Int,
    val name: String,
    val brand: String,
    val price: Double,
    val offersPrice: Double,
    val offersPercent: String,
    val money: String,
    val freeSend: Boolean,
    val promotion: Promotion,
    val date: String,
    val isFavorite: Boolean,
    val isPromotion: Boolean,
    val owner: Owner,
    val sold: Int,
    val punctuation: Double,
    val oldPrice: Double,
    val description: String,
    val discount: String,
    val sendPrice: Double,
    val location: String,
    val url: String
)

data class Promotion(val price: Double, val dues: Int, val cards: Cards)
data class Owner(val name: String, val alias: String)
data class Cards(val card1: String, val card2: String)